#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import argparse
import os
import sys
import yaml

def deploy(args):
    os.chdir(args.directory)

    # Load configuration
    try:
        with open(args.config) as conf:
            configuration = yaml.safe_load(conf)
    except FileNotFoundError:
        print("Error: No such file", args.config)
        return 1

    # Load secrets
    try:
        with open(args.secrets) as sec:
            secrets = yaml.safe_load(sec)
    except FileNotFoundError:
        secrets = dict()

    # Get files
    if "files" in configuration:
        files = configuration["files"]
    else:
        files = dict()
        print("Warning: no files in configuration.")

    # Get variables and update them with secrets
    if "variables" in configuration:
        variables = configuration["variables"]
    else:
        variables = dict()
    variables.update(secrets)

    for filename in files:
        deploy_file(filename, files[filename], variables,
                args.verbose, args.dry_run)


def deploy_file(src_filename, dst_filename, variables, verbose, dry_run):
    src_filename = src_filename.replace("~", os.path.expanduser("~"))
    dst_filename = dst_filename.replace("~", os.path.expanduser("~"))
    if verbose: print("Copying", src_filename, "to", dst_filename)
    if dry_run: return
    try:
        with open(src_filename, "rb") as src:
            try:
                os.makedirs(os.path.split(dst_filename)[0])
            except FileExistsError: pass
            mode = os.stat(src_filename).st_mode
            with open(dst_filename, "wb") as dst:
                content = src.read()
                for var in variables:
                    content = content.replace(b"{{ " + var.encode() + b" }}",
                            variables[var].encode())
                dst.write(content)
            os.chmod(dst_filename, mode)
    except FileNotFoundError:
        print("Warning: File", src_filename, "not found, skipping...")
    except IsADirectoryError:
        if verbose: print("Recursing into", src_filename)
        try:
            os.makedirs(dst_filename)
        except FileExistsError: pass
        for file in os.listdir(src_filename):
            deploy_file(os.path.join(src_filename, file),
                    os.path.join(dst_filename, file),
                    variables, verbose, dry_run)


def add_or_remove(args):
    field = "files" if not args.var else "variables"

    os.chdir(args.directory)
    try:
        with open(args.config) as conf:
            config = yaml.safe_load(conf)
    except FileNotFoundError:
        print("No file " + args.config + ", will create.")
        config = dict()

    if field not in config:
        config[field] = dict()

    if 'dst' in args:
        # Insert
        if args.verbose:
            print("Inserting value into configuration, before:")
            print(config[field])
        if not args.dry_run: config[field][args.src] = args.dst
        if args.verbose:
            print("After:")
            print(config[field])
    else:
        if args.verbose:
            print("Removing value from configuration, before:")
            print(config[field])
        if not args.dry_run :
            if args.src in config[field]:
                del config[field][args.src]
            else:
                print("Warning: No value", args.src, "in configuration.")
        if args.verbose:
            print("After:")
            print(config[field])

    try:
        with open(args.config, "w") as conf:
            yaml.safe_dump(config, conf, allow_unicode=True, default_flow_style=False)
    except:
        print("Error writing configuration to", args.config)


def main():
    parser = argparse.ArgumentParser(
            description="A small dotfile manager and templater.")
    subparsers = parser.add_subparsers()

    parser.add_argument("-d", "--directory", default=".",
            help="Do all operations relative to this directory. Default is .")
    parser.add_argument("-c", "--config", default="dotter.yml",
            help="Config file for dotter. Default is dotter.yml")
    parser.add_argument("-s", "--secrets", default="secrets.yml",
            help="Secrets file for dotter, doesn't have to exist." +
            "Default is secrets.yml")
    parser.add_argument("-v", "--verbose", action='store_true',
            help="Print information about what's being done.")
    parser.add_argument("--dry-run", action='store_true',
            help="Dry run - don't do anything, only print information.")

    deploy_parser = subparsers.add_parser('deploy',
            help="deploy -h",
            description="Copy all files to their configured locations.")
    deploy_parser.set_defaults(func=deploy)

    add_parser = subparsers.add_parser('add',
            help="add -h",
            description="Add a file to the configuration.")
    add_parser.add_argument(
    add_parser.add_argument("src",
            help="Source file")
    add_parser.add_argument("dst",
            help="Destination location")
    add_parser.set_defaults(func=add_or_remove)

    add_parser = subparsers.add_parser('remove',
            help="remove -h",
            description="Remove a file from the configuration.")
    add_parser.add_argument("src",
            help="Source file to be removed")
    add_parser.set_defaults(func=add_or_remove)

    args = parser.parse_args()

    if 'func' not in args:
        parser.print_help()
        return

    if args.dry_run:
        args.verbose = True

    exit_code = args.func(args)
    if exit_code: exit(exit_code)

if __name__ == "__main__":
    main()

# vim:nolist:
