#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import argparse
import os
import sys
import yaml

def deploy(args):
    os.chdir(args.directory)

    # Load configuration
    try:
        with open(args.config) as conf:
            configuration = yaml.safe_load(conf)
    except FileNotFoundError:
        print("No such file", args.config)
        return 1

    # Load secrets
    try:
        with open(args.secrets) as sec:
            secrets = yaml.safe_load(sec)
    except FileNotFoundError:
        secrets = dict()

    # Get files
    if "files" in configuration:
        files = configuration["files"]
    else:
        files = dict()
        print("Warning: no files in configuration.")

    # Get variables and update them with secrets
    if "variables" in configuration:
        variables = configuration["variables"]
    else:
        variables = dict()
    variables.update(secrets)

    for filename in files:
        deploy_file(filename, files[filename], variables)


def deploy_file(src_filename, dst_filename, variables):
    src_filename = src_filename.replace("~", os.path.expanduser("~"))
    dst_filename = dst_filename.replace("~", os.path.expanduser("~"))
    try:
        with open(src_filename) as src:
            try:
                os.makedirs(os.path.split(dst_filename)[0])
            except FileExistsError: pass
            with open(dst_filename, "w") as dst:
                content = src.read()
                for var in variables:
                    content = content.replace("{{ " + var + " }}", variables[var])
                dst.write(content)
    except FileNotFoundError:  # No such file
        print("Warning: File", src_filename, "not found, skipping...")


def main():
    parser = argparse.ArgumentParser(prog="Dotfiler",
            description="A small dotfile manager and templater.")
    parser.add_argument("-d", "--directory", default=".", help="Do all operations relative to this directory. Default is .")
    parser.add_argument("-c", "--config", default="dotter.yml", help="Config file for dotter. Default is dotter.yml")
    parser.add_argument("-s", "--secrets", default="secrets.yml", help="Secrets file for dotter, doesn't have to exist. Default is secrets.yml")

    args = parser.parse_args()
    exit_code = deploy(args)
    if exit_code: exit(exit_code)

if __name__ == "__main__":
    main()

# vim:nolist:
